[project]
name = "practice"
version = "0.1.0"
description = "Practice project with text, imag, audio, video branches"
authors = [
    { name="Hyenseok", email="hyenseok44@gmail.com" }
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
